# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'membraneCrackGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 713)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(85, 195, 188);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.Tabs.setFont(font)
        self.Tabs.setMouseTracking(False)
        self.Tabs.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Tabs.setAutoFillBackground(False)
        self.Tabs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tabs.setObjectName("Tabs")
        self.crackSegmentation = QtWidgets.QWidget()
        self.crackSegmentation.setStyleSheet("")
        self.crackSegmentation.setObjectName("crackSegmentation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.crackSegmentation)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.crackSegmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, -1, -1, 14)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label_16 = QtWidgets.QLabel(self.crackSegmentation)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.le_segInput = QtWidgets.QLineEdit(self.crackSegmentation)
        self.le_segInput.setStyleSheet("")
        self.le_segInput.setObjectName("le_segInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_segInput)
        self.label_15 = QtWidgets.QLabel(self.crackSegmentation)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.le_segSaveLoc = QtWidgets.QLineEdit(self.crackSegmentation)
        self.le_segSaveLoc.setObjectName("le_segSaveLoc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_segSaveLoc)
        self.le_segSaveName = QtWidgets.QLineEdit(self.crackSegmentation)
        self.le_segSaveName.setObjectName("le_segSaveName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_segSaveName)
        self.label_17 = QtWidgets.QLabel(self.crackSegmentation)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_startSeg = QtWidgets.QPushButton(self.crackSegmentation)
        self.btn_startSeg.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_startSeg.sizePolicy().hasHeightForWidth())
        self.btn_startSeg.setSizePolicy(sizePolicy)
        self.btn_startSeg.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.btn_startSeg.setFont(font)
        self.btn_startSeg.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 195, 188);\n"
"    border: solid rgb(49, 113, 108);\n"
"    border-width: 0px 1px 1px 0px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"QPushButton:disabled { \n"
"    background-color: rgb(140, 140, 140);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_startSeg.setObjectName("btn_startSeg")
        self.horizontalLayout_2.addWidget(self.btn_startSeg)
        self.btn_helpSeg = QtWidgets.QToolButton(self.crackSegmentation)
        self.btn_helpSeg.setEnabled(True)
        self.btn_helpSeg.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.btn_helpSeg.setFont(font)
        self.btn_helpSeg.setStyleSheet("QToolButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: solid rgb(79, 79, 79);\n"
"    border-width: 0px 1px 1px 0px;\n"
"    border-radius: 10px;\n"
"    padding: 0px 4px 0px 4px;\n"
"    color: white;\n"
"}\n"
"QToolButton:disabled { \n"
"    background-color: rgb(140, 140, 140);\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_helpSeg.setObjectName("btn_helpSeg")
        self.horizontalLayout_2.addWidget(self.btn_helpSeg)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.crackSegmentation)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.seg_output = QtWidgets.QTextBrowser(self.crackSegmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seg_output.sizePolicy().hasHeightForWidth())
        self.seg_output.setSizePolicy(sizePolicy)
        self.seg_output.setMinimumSize(QtCore.QSize(0, 94))
        self.seg_output.setMaximumSize(QtCore.QSize(16777215, 140))
        self.seg_output.setObjectName("seg_output")
        self.verticalLayout.addWidget(self.seg_output)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.frame = QtWidgets.QFrame(self.crackSegmentation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("border: solid rgb(80,80,80);\n"
"border-width: 2px 2px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget_2 = MplWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 801, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("border: solid rgb(80,80,80);\n"
"border-width: 2px 2px;")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.raise_()
        self.widget_2.raise_()
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 3)
        self.Tabs.addTab(self.crackSegmentation, "")
        self.crackAnalysis = QtWidgets.QWidget()
        self.crackAnalysis.setObjectName("crackAnalysis")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.crackAnalysis)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.output = QtWidgets.QTextBrowser(self.crackAnalysis)
        self.output.setMinimumSize(QtCore.QSize(800, 100))
        self.output.setStyleSheet("padding: 0px 4px 4px 4px;")
        self.output.setObjectName("output")
        self.gridLayout_3.addWidget(self.output, 4, 0, 1, 4)
        self.btn_helpAn = QtWidgets.QToolButton(self.crackAnalysis)
        self.btn_helpAn.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.btn_helpAn.setFont(font)
        self.btn_helpAn.setStyleSheet("QToolButton {\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: solid rgb(79, 79, 79);\n"
"    border-width: 0px 1px 1px 0px;\n"
"    border-radius: 10px;\n"
"    padding: 0px 4px 0px 4px;\n"
"    color: white;\n"
"}\n"
"QToolButton:disabled { \n"
"    background-color: rgb(140, 140, 140);\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_helpAn.setObjectName("btn_helpAn")
        self.gridLayout_3.addWidget(self.btn_helpAn, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("padding: 0px 0px 0px 4px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.formLayout_2.setHorizontalSpacing(7)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("padding:4px 0px 0px 0px;")
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_input = QtWidgets.QLineEdit(self.crackAnalysis)
        self.le_input.setObjectName("le_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.le_input)
        self.label_2 = QtWidgets.QLabel(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_saveLoc = QtWidgets.QLineEdit(self.crackAnalysis)
        self.le_saveLoc.setObjectName("le_saveLoc")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.le_saveLoc)
        self.label_3 = QtWidgets.QLabel(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.le_saveName = QtWidgets.QLineEdit(self.crackAnalysis)
        self.le_saveName.setObjectName("le_saveName")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.le_saveName)
        self.label_5 = QtWidgets.QLabel(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_pxSz = QtWidgets.QLineEdit(self.crackAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_pxSz.sizePolicy().hasHeightForWidth())
        self.le_pxSz.setSizePolicy(sizePolicy)
        self.le_pxSz.setObjectName("le_pxSz")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_pxSz)
        self.label_6 = QtWidgets.QLabel(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.sb_areaOpen = QtWidgets.QSpinBox(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.sb_areaOpen.setFont(font)
        self.sb_areaOpen.setMinimum(5)
        self.sb_areaOpen.setMaximum(30)
        self.sb_areaOpen.setObjectName("sb_areaOpen")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.sb_areaOpen)
        self.cb_saveData = QtWidgets.QCheckBox(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.cb_saveData.setFont(font)
        self.cb_saveData.setAcceptDrops(False)
        self.cb_saveData.setAutoFillBackground(False)
        self.cb_saveData.setChecked(True)
        self.cb_saveData.setObjectName("cb_saveData")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.cb_saveData)
        self.cb_saveVis = QtWidgets.QCheckBox(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.cb_saveVis.setFont(font)
        self.cb_saveVis.setObjectName("cb_saveVis")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.cb_saveVis)
        self.cb_ShapeOrient = QtWidgets.QCheckBox(self.crackAnalysis)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(False)
        font.setWeight(50)
        self.cb_ShapeOrient.setFont(font)
        self.cb_ShapeOrient.setObjectName("cb_ShapeOrient")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.cb_ShapeOrient)
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 2, 1, 2)
        self.btn_startAn = QtWidgets.QPushButton(self.crackAnalysis)
        self.btn_startAn.setEnabled(True)
        self.btn_startAn.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.btn_startAn.setFont(font)
        self.btn_startAn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 195, 188);\n"
"    border: solid rgb(49, 113, 108);\n"
"    border-width: 0px 1px 1px 0px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"QPushButton:disabled { \n"
"    background-color: rgb(140, 140, 140);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_startAn.setObjectName("btn_startAn")
        self.gridLayout_3.addWidget(self.btn_startAn, 2, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.crackAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("border: solid rgb(80,80,80);\n"
"border-width: 2px 2px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.canvas_1 = MplWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.canvas_1.sizePolicy().hasHeightForWidth())
        self.canvas_1.setSizePolicy(sizePolicy)
        self.canvas_1.setObjectName("canvas_1")
        self.gridLayout_5.addWidget(self.canvas_1, 0, 0, 2, 2)
        self.btn_right = QtWidgets.QToolButton(self.page)
        self.btn_right.setObjectName("btn_right")
        self.gridLayout_5.addWidget(self.btn_right, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_left = QtWidgets.QToolButton(self.page_2)
        self.btn_left.setObjectName("btn_left")
        self.gridLayout_4.addWidget(self.btn_left, 0, 3, 1, 1)
        self.canvas_2 = MplWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.canvas_2.sizePolicy().hasHeightForWidth())
        self.canvas_2.setSizePolicy(sizePolicy)
        self.canvas_2.setStyleSheet("")
        self.canvas_2.setObjectName("canvas_2")
        self.gridLayout_4.addWidget(self.canvas_2, 0, 2, 2, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 3, 2)
        self.Tabs.addTab(self.crackAnalysis, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 26))
        self.menubar.setObjectName("menubar")
        self.menuDocumentation = QtWidgets.QMenu(self.menubar)
        self.menuDocumentation.setObjectName("menuDocumentation")
        MainWindow.setMenuBar(self.menubar)
        self.ac_an = QtWidgets.QAction(MainWindow)
        self.ac_an.setObjectName("ac_an")
        self.ac_ = QtWidgets.QAction(MainWindow)
        self.ac_.setObjectName("ac_")
        self.menubar.addAction(self.menuDocumentation.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Membrane Crack Segmentation and Analysis"))
        self.label_8.setText(_translate("MainWindow", "Input"))
        self.label_16.setText(_translate("MainWindow", "Save Location"))
        self.label_15.setText(_translate("MainWindow", "Input File"))
        self.label_17.setText(_translate("MainWindow", "Save Name"))
        self.btn_startSeg.setText(_translate("MainWindow", "Start Segmentation"))
        self.btn_helpSeg.setText(_translate("MainWindow", "?"))
        self.label_7.setText(_translate("MainWindow", "Output"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.crackSegmentation), _translate("MainWindow", "Crack Segmentation"))
        self.btn_helpAn.setText(_translate("MainWindow", "?"))
        self.label_4.setText(_translate("MainWindow", "Output"))
        self.label.setText(_translate("MainWindow", "Input File"))
        self.label_2.setText(_translate("MainWindow", "Save Location"))
        self.label_3.setText(_translate("MainWindow", "Save Name"))
        self.label_5.setText(_translate("MainWindow", "Pixel Size (um)"))
        self.label_6.setText(_translate("MainWindow", "Minimum Object Size (Pixels)"))
        self.cb_saveData.setText(_translate("MainWindow", "Save Data"))
        self.cb_saveVis.setText(_translate("MainWindow", "Save Visuals"))
        self.cb_ShapeOrient.setText(_translate("MainWindow", "Analyze Shape/ Orientation"))
        self.btn_startAn.setText(_translate("MainWindow", "Start Analysis"))
        self.btn_right.setText(_translate("MainWindow", ">"))
        self.btn_left.setText(_translate("MainWindow", "<"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.crackAnalysis), _translate("MainWindow", "Crack Analysis"))
        self.menuDocumentation.setTitle(_translate("MainWindow", "Documentation"))
        self.ac_an.setText(_translate("MainWindow", "Segmentation"))
        self.ac_.setText(_translate("MainWindow", "Analysis Input"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

