# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_v011.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(643, 528)
        icon = QtGui.QIcon("Lib/Images/MemSeg.svg")
        #icon.addPixmap(QtGui.QPixmap("Lib/Images/MemSeg.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Cat_T = QtWidgets.QRadioButton(Dialog)
        self.Cat_T.setChecked(False)
        self.Cat_T.setObjectName("Cat_T")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.Cat_T)
        self.gridLayout.addWidget(self.Cat_T, 2, 2, 1, 1)
        self.An_B = QtWidgets.QRadioButton(Dialog)
        self.An_B.setChecked(False)
        self.An_B.setObjectName("An_B")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.An_B)
        self.gridLayout.addWidget(self.An_B, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.Help = QtWidgets.QToolButton(Dialog)
        self.Help.setObjectName("Help")
        self.gridLayout.addWidget(self.Help, 11, 1, 1, 1)
        self.Mask_check = QtWidgets.QCheckBox(Dialog)
        self.Mask_check.setIconSize(QtCore.QSize(16, 16))
        self.Mask_check.setChecked(True)
        self.Mask_check.setObjectName("Mask_check")
        self.gridLayout.addWidget(self.Mask_check, 3, 1, 1, 1)
        self.Cat_B = QtWidgets.QRadioButton(Dialog)
        self.Cat_B.setChecked(True)
        self.Cat_B.setObjectName("Cat_B")
        self.buttonGroup_2.addButton(self.Cat_B)
        self.gridLayout.addWidget(self.Cat_B, 2, 3, 1, 1)
        self.An_T = QtWidgets.QRadioButton(Dialog)
        self.An_T.setChecked(True)
        self.An_T.setObjectName("An_T")
        self.buttonGroup.addButton(self.An_T)
        self.gridLayout.addWidget(self.An_T, 1, 2, 1, 1)
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setObjectName("Cancel")
        self.gridLayout.addWidget(self.Cancel, 11, 8, 1, 1)
        self.GS_in = QtWidgets.QLineEdit(Dialog)
        self.GS_in.setObjectName("GS_in")
        self.gridLayout.addWidget(self.GS_in, 4, 1, 1, 3)
        self.Filter_size = QtWidgets.QSpinBox(Dialog)
        self.Filter_size.setProperty("value", 20)
        self.Filter_size.setObjectName("Filter_size")
        self.gridLayout.addWidget(self.Filter_size, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 4, 1, 1)
        self.An_check = QtWidgets.QCheckBox(Dialog)
        self.An_check.setChecked(True)
        self.An_check.setObjectName("An_check")
        self.gridLayout.addWidget(self.An_check, 1, 1, 1, 1)
        self.Cat_check = QtWidgets.QCheckBox(Dialog)
        self.Cat_check.setChecked(True)
        self.Cat_check.setObjectName("Cat_check")
        self.gridLayout.addWidget(self.Cat_check, 2, 1, 1, 1)
        self.Start = QtWidgets.QPushButton(Dialog)
        self.Start.setDefault(False)
        self.Start.setObjectName("Start")
        self.gridLayout.addWidget(self.Start, 11, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 14, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 14, 6, 1, 3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 2, 1, 1)
        self.FCReL_logo = QtWidgets.QLabel(Dialog)
        self.FCReL_logo.setText("")
        self.FCReL_logo.setPixmap(QtGui.QPixmap("Lib/Images/FCReL_logo.jpg"))
        self.FCReL_logo.setObjectName("FCReL_logo")
        self.gridLayout.addWidget(self.FCReL_logo, 0, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 4, 1, 2)
        self.Slc_loc = QtWidgets.QDoubleSpinBox(Dialog)
        self.Slc_loc.setMaximum(1.0)
        self.Slc_loc.setSingleStep(0.1)
        self.Slc_loc.setProperty("value", 0.5)
        self.Slc_loc.setObjectName("Slc_loc")
        self.gridLayout.addWidget(self.Slc_loc, 6, 4, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 5, 1, 2)
        self.Dir_input = QtWidgets.QLineEdit(Dialog)
        self.Dir_input.setObjectName("Dir_input")
        self.gridLayout.addWidget(self.Dir_input, 0, 1, 1, 4)
        self.Input_dir = QtWidgets.QPushButton(Dialog)
        self.Input_dir.setObjectName("Input_dir")
        self.gridLayout.addWidget(self.Input_dir, 0, 5, 1, 1)
        self.Out = QtWidgets.QListWidget(Dialog)
        self.Out.setObjectName("Out")
        self.gridLayout.addWidget(self.Out, 13, 1, 1, 4)
        self.FullDynSlc_Check = QtWidgets.QCheckBox(Dialog)
        self.FullDynSlc_Check.setObjectName("FullDynSlc_Check")
        self.gridLayout.addWidget(self.FullDynSlc_Check, 7, 4, 1, 1)
        self.MPL_ = MplWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPL_.sizePolicy().hasHeightForWidth())
        self.MPL_.setSizePolicy(sizePolicy)
        self.MPL_.setAutoFillBackground(False)
        self.MPL_.setObjectName("MPL_")
        self.gridLayout.addWidget(self.MPL_, 13, 5, 1, 4)
        self.DynSlcRng = QtWidgets.QLineEdit(Dialog)
        self.DynSlcRng.setObjectName("DynSlcRng")
        self.gridLayout.addWidget(self.DynSlcRng, 7, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 6, 1, 1)
        self.Num_steps = QtWidgets.QSpinBox(Dialog)
        self.Num_steps.setObjectName("Num_steps")
        self.gridLayout.addWidget(self.Num_steps, 7, 7, 1, 1)
        self.num_steps_label = QtWidgets.QLabel(Dialog)
        self.num_steps_label.setObjectName("num_steps_label")
        self.gridLayout.addWidget(self.num_steps_label, 7, 8, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MemSeg"))
        self.Cat_T.setText(_translate("Dialog", "Top"))
        self.An_B.setText(_translate("Dialog", "Bottom"))
        self.label_6.setText(_translate("Dialog", "Boundary"))
        self.Help.setText(_translate("Dialog", "Help"))
        self.Mask_check.setText(_translate("Dialog", "Create mask"))
        self.Cat_B.setText(_translate("Dialog", "Bottom"))
        self.An_T.setText(_translate("Dialog", "Top"))
        self.Cancel.setText(_translate("Dialog", "Cancel"))
        self.label_7.setText(_translate("Dialog", "Boundary"))
        self.An_check.setText(_translate("Dialog", "Anode"))
        self.Cat_check.setText(_translate("Dialog", "Cathode"))
        self.Start.setText(_translate("Dialog", "Start"))
        self.label_5.setText(_translate("Dialog", "Output"))
        self.label_2.setText(_translate("Dialog", "Filter size"))
        self.label_3.setText(_translate("Dialog", "Greyscale image name"))
        self.label.setText(_translate("Dialog", "Dynamic Slice location"))
        self.Input_dir.setText(_translate("Dialog", "Input Directory"))
        self.FullDynSlc_Check.setText(_translate("Dialog", "Full Dynamic Slice"))
        self.DynSlcRng.setText(_translate("Dialog", "0.2,0.8"))
        self.label_4.setText(_translate("Dialog", "Range"))
        self.num_steps_label.setText(_translate("Dialog", "Number of steps"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
